### Configuration parameters for the csRNAseq pipeline

sample_table: "config/samples.tsv"

chrom_sizes: "/Users/gok24jef/arabidopsis/ens/chrom.sizes"

genome_fasta: "/Users/gok24jef/arabidopsis/ens/genome.fa"

program:
  # Path to genome index for read alignment
  genome_index: "/Users/gok24jef/arabidopsis/ens/bwa/genome.fa"
  bfqutils:
    # Sequencing adapter for trimming single-end reads
    sequencing_adapter: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
    use_pigz: True
    pigz_threads: 4
  # Number of threads for alignment per sample (will not surpass --cores)
  alignment_threads: 4
  # Alignment program: [bwa-aln, bwa-mem, STAR, bowtie2]
  alignment_program: "bwa-aln"
  # Should trimmed FastQ files be kept?
  keep_trimmed_fastq: True
  # Should BAM files be kept?
  keep_bam: True
  # bwa aln-specific parameters:
  bwa_aln:
    # Should intermediate .sai files be kept?
    keep_sai: True
  bwa_mem:
    # Max gap size:
    w: 0
    # Clipping penalty:
    L: 999
    # Gap open penalty:
    O: 999
  bowtie2:
    extra_params: "--very-sensitive"
  hisat2:
    extra_params: "--very-sensitive --no-spliced-alignment --no-softclip"
  star:
    read_files_command: "zcat"
    align_ends_type: "EndToEnd"
    align_intron_max: 1
    out_filter_multimap_nmax: 1000
    # For small genomes lower this: min(14, floor(log2(genome_size_bp) / 2 - 1))
    # e.g. 12 for Arabidopsis (~135 Mb)
    genome_sa_index_nbases: 14
  homer:
    genome: "tair10"
    tagdir:
      extra_args: "-checkGC"
    tss:
      size: 100
      ntagthreshold: 5
      extra_args: "-includeSingleExons"


filtering:
  # Minimum alignment MAPQ:
  alignment_mapq: 30
  include_flags: 0
  exclude_flags: 2308
  # Max read length allowed after merging/trimming:
  max_read_length: 70
  min_alignment_length: 15
  max_mismatch: 999
  tss_min_reps: 1
  mask_srnas_from_bw: True

files:
  # What is root output folder for results?
  # (QC, BEDs, quantification, TSSs, HOMER tag directories, bedGraphs, bigWigs)
  output_dir: "results"
  # What is the root output folder for intermediate files?
  # (Trimmed FastQ, SAI, BAM)
  intermediate_dir: "results"

qc:
  mirnas: "/Users/gok24jef/csRNAseq/data/Araport11_miRNA.bed"
  trnas: "/Users/gok24jef/csRNAseq/data/Araport11_pre-tRNA.bed"
  min_cs_frip: 0.9
  min_pct_nuclear: 90
